<script setup lang="ts">
import { computed, ref } from 'vue'
import TrendChart from './TrendChart.vue'
import './monitor.css'

const props = defineProps<{ data: any; language: 'zh' | 'en' }>()
const t = (zh: string, en: string) => props.language === 'zh' ? zh : en
const monitor = computed(() => props.data.monitor ?? {})
const stats = computed(() => props.data.stats ?? {})
const live = computed(() => props.data.engine?.state === 'Running' && monitor.value.latest?.valid && !props.data.statsError)
const latest = computed(() => live.value ? monitor.value.latest : {})
const windowStats = computed(() => monitor.value.window ?? {})
const counts = computed(() => monitor.value.counts ?? {})
const throughputSeconds = computed(() => monitor.value.throughputWindowSeconds ?? 10)
const throughputHelp = computed(() => t(
  `每 2 秒采样，Prefill 和 Decode 分别判断。该项 token 增量为 0 时不更新速度，保留上次有效值；有增量时，按最近 ${throughputSeconds.value} 秒内非零采样的 token 增量 ÷ 对应采样时长计算平均。尚无有效值时显示 —；缺测、停止或重启后清空并重新计算。曲线同样保留零采样之前的值。`,
  `Sampled every 2s, independently for Prefill and Decode. A zero token delta keeps the last valid rate. A positive delta updates the average using non-zero intervals within the last ${throughputSeconds.value}s: token deltas divided by their combined duration. Shows — before the first valid rate; missing data, stops and restarts clear the value. Charts also hold the previous value during zero samples.`))
const memory = computed(() => stats.value.memory?.cuda_residency ?? {})
const occupancy = computed(() => stats.value.occupancy ?? {})
const capacity = computed(() => stats.value.capacity ?? {})
const cache = computed(() => stats.value.context_cache ?? {})
const pressure = computed(() => cache.value.pressure ?? {})
const latestRequest = computed(() => (props.data.recentRequests ?? []).find((r: any) => r.event === 'request_done') ?? {})
const selectedSeconds = ref(1800)
const history = computed(() => {
  const points = monitor.value.history ?? []
  const cutoff = (points.at(-1)?.t ?? Date.now()) - selectedSeconds.value * 1000
  return points.filter((p: any) => p.t >= cutoff)
})
const number = (raw: any, digits = 1) => raw === undefined || raw === null || !Number.isFinite(Number(raw)) ? '—' : Number(raw).toLocaleString(props.language === 'zh' ? 'zh-CN' : 'en-US', { maximumFractionDigits: digits })
const pct = (raw: any) => raw === undefined || raw === null ? '—' : number(raw * 100) + '%'
const unit = (raw: any, divisor: number, digits = 1) => raw === undefined || raw === null ? '—' : number(raw / divisor, digits)
const bytes = (raw: any) => {
  if (raw === undefined || raw === null || !Number.isFinite(Number(raw))) return '—'
  const value = Number(raw)
  return Math.abs(value) >= 1073741824 ? unit(value, 1073741824, 2) + ' GiB' : Math.abs(value) >= 1048576 ? unit(value, 1048576) + ' MiB' : Math.abs(value) >= 1024 ? unit(value, 1024) + ' KiB' : number(value, 0) + ' B'
}
const stamp = (raw: any) => {
  if (raw === undefined || raw === null) return '—'
  const date = new Date(raw)
  return Number.isNaN(date.getTime()) ? '—' : date.toLocaleTimeString(props.language === 'zh' ? 'zh-CN' : 'en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
}
const sum = (...values: any[]) => values.every(v => v == null) ? null : values.reduce((a, b) => a + (typeof b === 'number' ? b : 0), 0)
const ratio = (used: any, total: any) => used != null && total > 0 ? Math.max(0, Math.min(100, used / total * 100)) : 0
const sharedDelta = computed(() => memory.value.shared_bytes == null || memory.value.shared_baseline_bytes == null ? null : Math.max(0, memory.value.shared_bytes - memory.value.shared_baseline_bytes))
const cumulative = (direction: string, field: string) => sum(cache.value.main_kv_transfers?.[direction]?.[field], cache.value.backend_kv_transfers?.[direction]?.[field])
function requestStatus(r: any) { return r.event === 'request_done' ? t('完成', 'Completed') : r.event === 'request_error' ? t('错误', 'Error') : r.event === 'request_rejected' ? t('拒绝', 'Rejected') : r.event ?? '—' }
function requestProc(r: any) {
  if (r.proc_ms != null) return r.proc_ms
  const ttft = r.timings_seconds?.ttft, queue = r.engine_timing?.queue_wait_seconds
  return typeof ttft === 'number' && typeof queue === 'number' && queue >= 0 && queue <= ttft ? (ttft - queue) * 1000 : null
}
const mtpRequests = computed(() => (props.data.recentRequests ?? []).filter((r: any) => (r.spec_drafted ?? r.speculative?.drafted_tokens ?? 0) > 0).slice(0, 12))
const series = (key: string, label: string, color = '#07896b', scale = 1) => ({ key, label, color, scale })
const charts = computed(() => [
  { title: t(`预填充吞吐 · ${throughputSeconds.value} 秒非零采样平均`, `Prefill throughput · ${throughputSeconds.value}s non-zero average`), unit: 'tok/s', series: [series('prefillTps', 'Prefill')] },
  { title: t(`生成吞吐 · ${throughputSeconds.value} 秒非零采样平均`, `Decode throughput · ${throughputSeconds.value}s non-zero average`), unit: 'tok/s', series: [series('decodeTps', 'Decode', '#4287cc')] },
  { title: t('首 token 延迟 · 最近一小时', 'Time to first token · trailing hour'), unit: 'ms', series: [series('ttftP50Ms', 'p50'), series('ttftP95Ms', 'p95', '#bd8142')] },
  { title: t('MTP 接受率 · 最近一小时', 'MTP acceptance · trailing hour'), unit: '%', ceiling: 100, series: [series('mtpAcceptanceRate', t('接受率', 'Acceptance'), '#8771bd', 100)] },
  { title: t('GPU 使用率', 'GPU utilization'), unit: '%', ceiling: 100, series: [series('gpuUtilizationPercent', 'GPU', '#4287cc')] },
  { title: t('GPU 功耗', 'GPU power'), unit: 'W', series: [series('gpuPowerWatts', t('实际功耗', 'Power draw'), '#bd8142'), series('gpuPowerLimitWatts', t('功率上限', 'Power limit'), '#adb8b1')] },
  { title: t('Device KV 占用', 'Device KV occupancy'), unit: 'tokens', series: [series('deviceKvTokens', t('KV tokens', 'KV tokens'))] },
  { title: t('Host KV 占用', 'Host KV occupancy'), unit: 'GiB', series: [series('hostKvBytes', 'Host KV', '#8771bd', 1 / 1073741824)] },
  { title: t('KV 搬运 · 每个采样区间', 'KV transfers · per sampling interval'), unit: 'MiB', series: [series('h2dBytes', 'H2D', '#07896b', 1 / 1048576), series('d2hBytes', 'D2H', '#c7784b', 1 / 1048576), series('d2dBytes', 'D2D', '#8771bd', 1 / 1048576)] },
  { title: t('显存驻留与整卡余量', 'Dedicated residency and device free memory'), unit: 'GiB', series: [series('dedicatedBytes', 'Dedicated', '#07896b', 1 / 1073741824), series('gpuFreeBytes', t('NVML 可用', 'NVML free'), '#4287cc', 1 / 1073741824)] },
  { title: t('调度状态', 'Scheduler activity'), unit: t('请求', 'requests'), series: [series('running', t('运行', 'Running')), series('prefilling', 'Prefill', '#4287cc'), series('waiting', t('等待', 'Waiting'), '#bd8142'), series('materializing', t('恢复中', 'Restoring'), '#8771bd')] }
])
</script>

<template>
 <div class="monitor-panel">
  <div class="monitor-statusline"><span><i class="dot" :class="{online:live}"></i>{{ live ? t('后台采样中', 'Background sampling active') : data.engine?.state === 'Running' ? t('等待引擎统计', 'Waiting for engine statistics') : t('引擎未运行 · 保留本轮历史', 'Engine inactive · retaining this run’s history') }} · {{ stamp(monitor.sampledAt) }}</span><span>{{ t('每 2 秒采样 · 本次运行保留 6 小时 · 刷新网页不丢历史', 'Sampled every 2s · 6h in memory for this run · page refresh preserves history') }}</span></div>
  <div v-if="data.statsError" class="monitor-note warning">{{ t('引擎统计暂不可用，趋势在缺失处断开。', 'Engine statistics are temporarily unavailable; missing samples appear as gaps.') }} {{ data.statsError }}</div>
  <div v-if="counts.catchingUp" class="monitor-note">{{ t('正在读取本次运行的请求日志，累计计数仍在更新。', 'Reading this run’s request log; cumulative counts are still catching up.') }}</div>

  <div class="metric-grid monitor-metrics">
   <article :title="throughputHelp"><small>{{ t(`Prefill · ${throughputSeconds} 秒非零采样平均`, `Prefill · ${throughputSeconds}s non-zero average`) }}</small><strong>{{ number(latest.prefillTps) }} <em>tok/s</em></strong><p>{{ t('每 2 秒采样 · 零值保留上次速度', 'Sampled every 2s · zero keeps the last rate') }}</p></article>
   <article :title="throughputHelp"><small>{{ t(`Decode · ${throughputSeconds} 秒非零采样平均`, `Decode · ${throughputSeconds}s non-zero average`) }}</small><strong>{{ number(latest.decodeTps) }} <em>tok/s</em></strong><p>{{ t('每 2 秒采样 · 零值保留上次速度', 'Sampled every 2s · zero keeps the last rate') }}</p></article>
   <article><small>{{ t('GPU 使用率', 'GPU utilization') }}</small><strong>{{ number(data.gpu?.utilizationPercent, 0) }} <em>%</em></strong><p>{{ t('温度', 'Temperature') }} {{ number(data.gpu?.temperatureC, 0) }} °C</p></article>
   <article><small>{{ t('GPU 功耗', 'GPU power') }}</small><strong>{{ number(data.gpu?.powerWatts, 0) }} <em>W</em></strong><p>{{ t('功率上限', 'Power limit') }} {{ number(data.gpu?.powerLimitWatts, 0) }} W</p></article>
  </div>
  <section class="panel monitor-latest"><div><h3>{{ t('最近完成请求', 'Latest completed request') }}</h3><p class="hint">{{ stamp(latestRequest.timestamp ?? latestRequest.timestamp_unix_ms) }} · {{ t('按该次请求实际处理耗时计算，和上方按采样窗口计算的速度口径不同。', 'Rates use this request’s processing time, rather than the sampling window used above.') }}</p></div><dl><div><dt>Prefill</dt><dd>{{ number(latestRequest.prefill_tps) }} tok/s</dd></div><div><dt>Decode</dt><dd>{{ number(latestRequest.decode_tps) }} tok/s</dd></div><div><dt>TTFT</dt><dd>{{ number(latestRequest.ttft_ms) }} ms</dd></div><div><dt>{{ t('输入 / 输出', 'Input / output') }}</dt><dd>{{ number(latestRequest.prompt_tokens, 0) }} / {{ number(latestRequest.completion_tokens, 0) }}</dd></div><div><dt>{{ t('思考 tokens', 'Thinking tokens') }}</dt><dd>{{ number(latestRequest.reasoning_tokens, 0) }}</dd></div></dl></section>

  <div class="monitor-grid">
   <section class="panel"><div class="panel-title"><h3>{{ t('请求与延迟', 'Requests and latency') }}</h3><span class="badge">{{ t('本次运行', 'This run') }}</span></div><div class="monitor-counts"><div><strong>{{ number(counts.completed, 0) }}</strong><small>{{ t('完成', 'Completed') }}</small></div><div><strong>{{ number(counts.errors, 0) }}</strong><small>{{ t('错误', 'Errors') }}</small></div><div><strong>{{ number(counts.rejected, 0) }}</strong><small>{{ t('拒绝', 'Rejected') }}</small></div></div><p class="monitor-subtitle">{{ t('最近一小时 · 仅已完成请求', 'Trailing hour · completed requests only') }}</p><dl><div><dt>TTFT · p50 / p95</dt><dd>{{ number(windowStats.ttftP50Ms) }} / {{ number(windowStats.ttftP95Ms) }} ms</dd></div><div><dt>{{ t('处理时间 · p50 / p95', 'Processing · p50 / p95') }}</dt><dd>{{ number(windowStats.procP50Ms) }} / {{ number(windowStats.procP95Ms) }} ms</dd></div><div><dt>Prefill · p50 / p95</dt><dd>{{ number(windowStats.prefillP50Tps) }} / {{ number(windowStats.prefillP95Tps) }} tok/s</dd></div><div><dt>Decode · p50 / p95</dt><dd>{{ number(windowStats.decodeP50Tps) }} / {{ number(windowStats.decodeP95Tps) }} tok/s</dd></div></dl><p class="hint">{{ t('处理时间 = TTFT − 排队时间。累计计数包含本次引擎运行全部已读取事件。', 'Processing time = TTFT − queue time. Counts include all read events from this engine run.') }}</p></section>
   <section class="panel"><div class="panel-title"><h3>{{ t('MTP / 推测解码', 'MTP / speculative decoding') }}</h3><span class="badge">{{ t('最近一小时', 'Trailing hour') }}</span></div><div class="monitor-big">{{ pct(windowStats.mtp?.acceptanceRate) }}<small>{{ t('草稿 token 接受率', 'Draft token acceptance') }}</small></div><dl><div><dt>{{ t('接受 / 草稿 tokens', 'Accepted / drafted tokens') }}</dt><dd>{{ number(windowStats.mtp?.accepted, 0) }} / {{ number(windowStats.mtp?.drafted, 0) }}</dd></div><div><dt>{{ t('草稿轮数', 'Draft rounds') }}</dt><dd>{{ number(windowStats.mtp?.rounds, 0) }}</dd></div><div><dt>{{ t('每轮接受 tokens', 'Accepted tokens / round') }}</dt><dd>{{ number(windowStats.mtp?.tokensPerRound, 2) }}</dd></div></dl><details class="monitor-details"><summary>{{ t('最近推测解码摘要', 'Recent speculative decoding') }}</summary><div class="mtp-entry" v-for="r in mtpRequests" :key="r.request_id"><span class="mono">{{ r.request_id }}</span><span>{{ r.speculative?.backend ?? 'MTP' }} · {{ number(r.spec_accept ?? r.speculative?.accepted_tokens, 0) }} / {{ number(r.spec_drafted ?? r.speculative?.drafted_tokens, 0) }} {{ t('接受', 'accepted') }} · {{ number(r.spec_rounds ?? r.speculative?.rounds, 0) }} {{ t('轮', 'rounds') }}</span></div><p v-if="!mtpRequests.length" class="hint">{{ t('暂无草稿记录。', 'No draft records yet.') }}</p></details></section>
   <section class="panel"><div class="panel-title"><h3>{{ t('前缀缓存与复用', 'Prefix cache and reuse') }}</h3><span class="badge">{{ t('最近一小时', 'Trailing hour') }}</span></div><div class="monitor-counts two"><div><strong>{{ pct(windowStats.cache?.tokenHitRate) }}</strong><small>{{ t('输入 token 命中率', 'Input token hit rate') }}</small></div><div><strong>{{ pct(windowStats.cache?.requestHitRate) }}</strong><small>{{ t('请求命中率', 'Request hit rate') }}</small></div></div><dl><div><dt>{{ t('命中 / 输入 tokens', 'Hit / input tokens') }}</dt><dd>{{ number(windowStats.cache?.hitTokens, 0) }} / {{ number(windowStats.cache?.promptTokens, 0) }}</dd></div><div><dt>{{ t('命中 / 完成请求', 'Hit / completed requests') }}</dt><dd>{{ number(windowStats.cache?.hitRequests, 0) }} / {{ number(windowStats.cache?.requests, 0) }}</dd></div></dl><div class="cache-paths"><div v-for="path in windowStats.cache?.paths ?? []" :key="path.path"><code>{{ path.path || t('无复用路径', 'No reuse path') }}</code><span>{{ number(path.requests, 0) }} {{ t('次', 'requests') }} · {{ number(path.hitTokens, 0) }} tokens</span><div class="monitor-bar"><i :style="{width:ratio(path.requests, windowStats.cache?.requests)+'%'}"></i></div></div><p v-if="!windowStats.cache?.paths?.length" class="hint">{{ t('完成请求后显示复用途径。', 'Reuse paths appear after completed requests.') }}</p></div></section>
   <section class="panel"><div class="panel-title"><h3>{{ t('显存驻留', 'VRAM residency') }}</h3><span class="badge" :class="{ok:memory.verified}">{{ memory.enabled ? (memory.verified ? t('验证通过', 'Verified') : t('未验证通过', 'Not verified')) : t('无驻留数据', 'No residency data') }}</span></div><div class="monitor-big">{{ bytes(data.gpu?.freeBytes) }}<small>{{ t('NVML 整卡剩余显存', 'NVML whole-device free memory') }}</small></div><dl><div><dt>Dedicated</dt><dd>{{ bytes(memory.dedicated_bytes) }}</dd></div><div><dt>{{ t('CUDA 报告可用', 'CUDA reported free') }}</dt><dd>{{ bytes(memory.cuda_free_bytes) }}</dd></div><div><dt>{{ t('Shared 基线 / 超出', 'Shared baseline / excess') }}</dt><dd>{{ bytes(memory.shared_baseline_bytes) }} / {{ bytes(sharedDelta) }}</dd></div><div><dt>{{ t('通过验证的预留', 'Verified reserve') }}</dt><dd>{{ bytes(memory.verified_reserve_bytes) }}</dd></div><div><dt>{{ t('NVML 已用 / 总量', 'NVML used / total') }}</dt><dd>{{ bytes(data.gpu?.usedBytes) }} / {{ bytes(data.gpu?.totalBytes) }}</dd></div></dl><p class="hint">{{ t('CUDA free、Dedicated 和 Shared 使用不同统计口径。Host cache 计入 Shared 基线。', 'CUDA free, Dedicated and Shared have different accounting scopes. Host cache contributes to the Shared baseline.') }}</p></section>
  </div>
  <div v-if="windowStats.truncated" class="monitor-note warning">{{ t('当前一小时统计已达到', 'The trailing-hour window reached its cap of') }} {{ number(windowStats.requestLimit,0) }} {{ t('条请求上限；分位数与命中率仅覆盖保留的最近请求。', 'requests; percentiles and hit rates cover only the retained most recent requests.') }}</div>

  <div class="monitor-grid">
   <section class="panel"><h3>{{ t('KV 容量与占用', 'KV capacity and occupancy') }}</h3><dl><div><dt>{{ t('Device 主 KV', 'Device main KV') }}</dt><dd>{{ number(occupancy.device_main_kv_pages,0) }} / {{ number(capacity.kv_capacity_pages,0) }} {{ t('页', 'pages') }}</dd></div></dl><div class="monitor-bar"><i :style="{width:ratio(occupancy.device_main_kv_pages,capacity.kv_capacity_pages)+'%'}"></i></div><dl><div><dt>{{ t('Device KV tokens', 'Device KV tokens') }}</dt><dd>{{ number(occupancy.device_main_kv_tokens,0) }}</dd></div><div><dt>Host KV</dt><dd>{{ bytes(occupancy.host_kv_bytes) }} / {{ bytes(capacity.host_kv_bytes) }}</dd></div></dl><div class="monitor-bar purple"><i :style="{width:ratio(occupancy.host_kv_bytes,capacity.host_kv_bytes)+'%'}"></i></div><dl><div><dt>{{ t('Host 状态槽位', 'Host state slots') }}</dt><dd>{{ number(occupancy.host_state_slots,0) }} / {{ number(capacity.host_state_slots,0) }}</dd></div><div><dt>{{ t('Device 状态槽位', 'Device state slots') }}</dt><dd>{{ number(occupancy.device_state_slots,0) }}</dd></div><div><dt>{{ t('Backend KV 页数', 'Backend KV pages') }}</dt><dd>{{ number(cache.occupancy?.device_backend_kv_pages,0) }}</dd></div></dl></section>
   <section class="panel"><h3>{{ t('KV 与状态搬运', 'KV and state transfers') }}</h3><p class="hint">{{ t('H2D：恢复到 GPU · D2H：转存到主机 · D2D：设备内复制', 'H2D: restore to GPU · D2H: park on host · D2D: device copy') }}</p><div class="table-wrap"><table class="transfer-table"><thead><tr><th>{{ t('方向', 'Direction') }}</th><th>{{ t('本区间 KV', 'Interval KV') }}</th><th>{{ t('累计 KV', 'Cumulative KV') }}</th><th>{{ t('累计耗时', 'Total time') }}</th></tr></thead><tbody><tr v-for="direction in ['h2d','d2h','d2d']" :key="direction"><td>{{ direction.toUpperCase() }}</td><td>{{ bytes(latest[direction+'Bytes']) }}</td><td>{{ bytes(cumulative(direction,'bytes')) }}</td><td>{{ number(cumulative(direction,'seconds'),2) }} s</td></tr></tbody></table></div><dl><div v-for="direction in ['h2d','d2h','d2d']" :key="direction"><dt>{{ t('状态', 'State') }} {{ direction.toUpperCase() }}</dt><dd>{{ number(cache.state_transfers?.[direction]?.count,0) }} {{ t('次', 'copies') }} · {{ bytes(cache.state_transfers?.[direction]?.bytes) }}</dd></div></dl></section>
  </div>
  <section class="panel"><div class="panel-title"><h3>{{ t('调度与缓存压力', 'Scheduler and cache pressure') }}</h3><span class="muted">{{ t('压力计数为引擎累计值', 'Pressure counters are engine totals') }}</span></div><div class="monitor-mini-grid"><div v-for="[key,zh,en] in [['running','运行','Running'],['prefilling','预填充','Prefilling'],['waiting','等待','Waiting'],['materializing','恢复中','Restoring'],['decode_ready','等待生成','Decode ready'],['capture_pending','等待图捕获','Graph capture'],['terminal_pending','等待结束','Terminal pending']]" :key="key"><small>{{ t(zh,en) }}</small><strong>{{ number(stats.scheduler?.[key],0) }}</strong></div><div><small>{{ t('已接纳 / 峰值', 'Admitted / peak') }}</small><strong>{{ number(stats.requests?.admitted,0) }} / {{ number(stats.requests?.peak_admitted,0) }}</strong></div></div><div class="monitor-pressure"><span>{{ t('溢出页数', 'Spilled pages') }} <b>{{ number(pressure.spill_pages,0) }}</b></span><span>{{ t('驱逐', 'Evicted owners') }} <b>{{ number(sum(pressure.private_owners_evicted,pressure.shared_owners_evicted),0) }}</b></span><span>{{ t('转存', 'Demoted owners') }} <b>{{ number(pressure.private_owners_demoted,0) }}</b></span><span>{{ t('降级', 'Degraded owners') }} <b>{{ number(sum(pressure.private_owners_degraded,pressure.shared_owners_degraded),0) }}</b></span><span>{{ t('回退', 'Fallbacks') }} <b>{{ number(pressure.maximal_fallback_selections,0) }}</b></span><span>{{ t('丢弃检查点', 'Dropped checkpoints') }} <b>{{ number(pressure.checkpoints_dropped,0) }}</b></span><span>{{ t('搜索 / 预算耗尽', 'Searches / exhausted') }} <b>{{ number(pressure.searches,0) }} / {{ number(pressure.search_budget_exhaustions,0) }}</b></span></div></section>

  <section class="panel monitor-trends"><div class="panel-title"><div><h3>{{ t('运行趋势', 'Runtime trends') }}</h3><p class="hint">{{ t('移动鼠标查看数值；缺失数据留空。峰值保留抽样，历史仅保存在管理器内存中。', 'Hover to inspect values. Missing data stays blank. Charts preserve sampled peaks; history is held in manager memory.') }}</p></div><div class="monitor-range" :aria-label="t('历史时间范围','History time range')"><button v-for="[seconds,label] in [[300,'5m'],[1800,'30m'],[3600,'1h'],[21600,'6h']]" :key="String(seconds)" :class="{selected:selectedSeconds===seconds}" :aria-pressed="selectedSeconds===seconds" @click="selectedSeconds=Number(seconds)">{{ label }}</button></div></div><div class="trend-grid"><TrendChart v-for="chart in charts" :key="chart.series[0].key" :title="chart.title" :unit="chart.unit" :series="chart.series" :ceiling="chart.ceiling" :points="history" :language="language"/></div><p class="hint">{{ throughputHelp }} {{ t('延迟和接受率来自各采样时刻的最近一小时窗口；GPU 与搬运指标保持原有 2 秒采样。', 'Latency and acceptance use the trailing-hour window at each sample; GPU and transfer metrics keep their 2s sampling interval.') }}</p></section>

  <section class="panel"><div class="panel-title"><h3>{{ t('最近请求', 'Recent requests') }}</h3><span class="muted">{{ t('最多显示 20 条 · 包含错误与拒绝', 'Up to 20 entries · includes errors and rejections') }}</span></div><div class="table-wrap"><table class="request-table"><thead><tr><th>{{ t('时间 / 请求', 'Time / request') }}</th><th>{{ t('协议 / 状态', 'Protocol / status') }}</th><th>{{ t('输入 / 输出 / 思考', 'Input / output / thinking') }}</th><th>TTFT / {{ t('处理', 'processing') }}</th><th>{{ t('缓存命中 / 复用路径', 'Cache hits / reuse path') }}</th><th>{{ t('结束原因 / 错误', 'Finish reason / error') }}</th></tr></thead><tbody><tr v-for="(r,i) in (data.recentRequests ?? []).slice(0,20)" :key="r.request_id ?? i"><td><span>{{ stamp(r.timestamp ?? r.timestamp_unix_ms) }}</span><small class="mono" :title="r.request_id">{{ String(r.request_id ?? '—').slice(-18) }}</small></td><td><span>{{ r.protocol ?? r.request?.protocol ?? '—' }}</span><small :class="{'request-error':r.event==='request_error'||r.event==='request_rejected'}">{{ requestStatus(r) }}</small></td><td>{{ number(r.prompt_tokens,0) }} / {{ number(r.completion_tokens,0) }} / {{ number(r.reasoning_tokens,0) }}</td><td>{{ number(r.ttft_ms) }} / {{ number(requestProc(r)) }} ms</td><td><span>{{ number(r.cached_tokens,0) }} tokens</span><small class="mono">{{ r.prefix_reuse_path ?? r.result?.prefix_reuse_path ?? '—' }}</small></td><td class="request-message"><span>{{ r.finish_reason ?? '—' }}</span><small class="request-error">{{ r.error_message ?? r.error?.message ?? r.error?.code ?? '' }}</small></td></tr><tr v-if="!data.recentRequests?.length"><td colspan="6" class="empty">{{ t('完成一次推理后，请求数据会显示在这里。', 'Request records appear after an inference completes.') }}</td></tr></tbody></table></div></section>
  <section class="panel"><details class="monitor-details"><summary>{{ t('完整引擎统计 /stats', 'Full engine statistics /stats') }}</summary><pre>{{ JSON.stringify(data.stats,null,2) }}</pre></details></section>
  <section class="panel"><h3>{{ t('运行日志', 'Engine log') }}</h3><pre class="logs">{{ Array.isArray(data.logTail) ? data.logTail.join('\n') : data.logTail || t('暂无运行日志。', 'No engine log yet.') }}</pre></section>
 </div>
</template>
